### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by agnelvishal** [ikreymer/cdx-index-client#11]
I get the error
```
Traceback (most recent call last):
  File "cdx-index-client.py", line 382, in <module>
    main()
  File "cdx-index-client.py", line 379, in main
    read_index(r, info['cdx-api'], info['id'])
  File "cdx-index-client.py", line 292, in read_index
    num_pages = get_num_pages(api_url, r.url, r.page_size)
  File "cdx-index-client.py", line 33, in get_num_pages
    pages_info = r.json()
  File "/root/commoncrawl-env-py3/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
when using the command `./cdx-index-client.py -c all http://skcript.com/* --fl url -d crawled`

**Comment by agnelvishal** [comment]
Could @ikreymer help?

**Comment by Chaitanya-Jadhav** [comment]
I got the same error.

**Comment by y0m** [comment]
Hello folks!

I had the same error (Ubuntu 20.4). Switching from python3 (which is the default Python version on Ubuntu) to python2.7 solved it.
